name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Build and deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Azureflask'
        slot-name: 'production'
        publish-profile: ${{ secrets.ASP-Azureflaskgitgroup-9184 }}
        package: .
